language: python
matrix:
  include:
  - python: 3.6
    dist: bionic
  - python: 3.7
    dist: bionic
    sudo: true
  - python: 3.8
    dist: bionic
    sudo: true
install:
- pip install -r tests_requirements.txt
- pip install coveralls
- gem install mdl
script:
- coverage run -m unittest discover
- flake8 canvasapi tests
- mdl . .github
- "./scripts/run_black.sh"
- python scripts/alphabetic.py
after_success:
- coveralls
notifications:
  slack:
    secure: oLrAMXKVN9EKOyvROg5ZZUQgeleKq6lsVslm/Jtg516LtdBnLiAA672xMrwB0m8UtSJvoz4m1BrBQBeO+OzxlmioJHDvm//MMXv8wpfBdi18ojBA/5wjYfYP4eta/9j1x4myWH9ygcJOdKhALOSt4fwKsmIRDt6YTensOaqcCTiS2YjtAWMLrKvlathpdMokx0k7FVluJJ+zEfzNote75AP7yq6nFFe9j0ALX7YuNFytshZXi82aKZpAuUGMNLjcL+B5acLKSYqF214sTVETPa2mrhja+89+W9512X3ecRdHPC6Ud10ICD6ap0XMrOcgNW8XREV0pDIDPrMJgSUFiFWMhvrkMjfnmJB2nrINPTc3CrMmmk8Hk1XYta+iA4yAEUb9dhkKmkxMZWtn7TZ7DiKaAXznwj6poGrnN+NXeWfoJ0j2pAUrcO4Jn9e43+ORMDYqCFV3QemtykbX0HKgVfOTx5F1ZBGULiMi7U3q5naieGep5j+OxNI9bcQMUoM6O+VxmkjtB1/8/F7PlKHrA/7Z1+s+1HM00lSvw5qAhkInPgkLU+X495+TsEfqJuVZIUIAS1jDDSuo3bTHHUYzDwE9UF/dYN/nVDiUEVa4xYe+UrAFuPnezL/bdezVwzoGd1Mb5HKJxs90wxYIZFkReivA1z4bQsYh+A/QbYKewR0=
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: pUwA7Nf2XOJcCSbe0/ikGjEaNQPXEjaMJCpx4DfHg4gONA3em8lQejMylqMyhNj5Gv4a9wS8BZBAXrw/ZPrWhVX6bmavoEu2wqZWFCClOVxl9s+UZD6NWRMCYfzV80baTDCf56Qyk9G/WTCk1n/5hYvK5kXWOWbdHeshSSWnZCKWweOmT5YAOidHQX2l0k64TLaT8jaEzQdBrVEj6Cq4YS9NYVcCX7dIt4cvX2t3Z518SOfuu2jBYjFiETFeMAWQie2cJNXiYv4IuhZZB7TsQJEMXjyU2BalD+pAlKz5nkY6d6NF5VsbYJcpc6hecfyiPvPBO+iK8hSJFabMxVbEl4/WguK9fXlX2L5ZqsKfYBgLZj77seBArQ8Kroja6wJstZEIxELsPr5cLGNNgsGkvhsvZ/Ls5RP79Am6r0Ow+8E0hTOrw2lW4CepoieAmusqClVqxWd6Ft887SIKXMy2HzZ6v3rsH8R/2e/lADfxjKXejGcRh2G7Lvmh52nLn/icWPLkHFUCizlDCnvXoh/eH/uPaRJrzK3Rq8udAmgu7GzDEwWGl4G/Mp303ndJiVSbEamx1ft9B48VLgHJChCgjt1E3mhSX7kPtowwkYUwzheYeStHOVcKm9WXWbxAGATbJ4rjpVM57iL22IeJZ7xqk946GBKhiTmiQc+oodbZx9U=
  on:
    tags: true
